pipeline{
    agent any 
    stages{
        stage("sonar quality checks "){
            agent {
                docker{
                    image 'opendk:11'
                }
            }
            steps{
                script{
                    withSonarQubeEnv(credentialsId: 'sonar-token') {
                 sh 'chmod +x gradlew'
                 sh './gradlew sonarqube'}

                }
            }
            
            }
        }
    }
   
}